blank_issues_enabled: false
contact_links:
  - name: ğŸ§‘â€ğŸ’» Anikku help discord
    url: https://discord.gg/85jB7V5AJR
    about: Common questions are answered here
  - name: ğŸ–¥ï¸ Anikku website
    url: https://anikku-app.github.io/
    about: Guides, troubleshooting, and answers to common questions
